### ISSUE TITLE
match_sensors() doesnt seem to work with SVC transmittance data?

### ISSUE THREAD

**Issue by serbinsh** [meireles/spectrolab#15] opened 2021-04-21 19:35 UTC
I am working on processing some additional transmittance data collected in Panama

![Original_SVC_spectra](https://user-images.githubusercontent.com/3067369/115610410-d23ea300-a2b6-11eb-845b-ca0e43ec6207.png)

 and switched from the branch 
```
devtools::install_github("meireles/spectrolab", ref = "splice_sensor_bug", force = TRUE, dependencies = T)
```

to master.  However when I hit the match_sensor() step I am getting the factor error again

```
> fixed_spectra <- spectrolab::match_sensors(spec.files, splice_at = c(vis_splice_wavelength, swir2_splice_wavelength), 
+                       fixed_sensor = 2, interpolate_wvl = interpolate_wvl)
Error in FUN(X[[i]], ...) : 
  Factors to match sensors are either NaN or are outside the bounds chosen by `factor_range`:1489101415182123252627293234353638414244455058596061
  ```

however with the same datasets the "splice_sensor_bug" version works fine?  I can process the data.  

That said, the new "master" version has been working with similar scripts of my for reflectance data so this seems to be an issue specific to transmittance data?

**Comment by meireles** [comment] 2021-05-09 01:00
@serbinsh First, sorry for the delay. The end of the semester is always a mess!

I'm not sure what is happening and I couldn't reproduce the error. I've updated the dev and master branches though. Can you reinstall it and see if things look better?

I've also added a [matching sensors vignette](https://github.com/meireles/spectrolab/files/6446786/match_sensors.pdf) as a sanity check and the function seems to work OK with radiance data.

**Comment by meireles** [comment] 2021-09-23 14:28
@serbinsh Is the problem fixed? Just wondering if we can close this issue.

**Comment by serbinsh** [comment] 2021-09-23 16:46
So sorry - I will check this afternoon and get back to you!

**Comment by serbinsh** [comment] 2021-09-23 17:16
@meireles yes, it looks like its working now.  even with the noised integrating sphere transmittance data

![Overlap_removed_and_matched_SVC_spectra](https://user-images.githubusercontent.com/3067369/134553718-6ecc54dd-7bd1-41d4-8d87-950fe4bf0a90.png)


[SVC_overlap_corrected_linear_interpolated_spectra_group_summary.pdf](https://github.com/meireles/spectrolab/files/7219561/SVC_overlap_corrected_linear_interpolated_spectra_group_summary.pdf)

**Comment by serbinsh** [comment] 2021-09-23 17:20
Yeah, I have run a few different directories of data and it seems to be working for me. Thanks!

**Comment by meireles** [comment] 2021-09-23 17:23
Great, thanks!

**Closed as completed by meireles** 2021-09-23 17:23 UTC
